[package]
name = "redis-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
redis = { version = "0.32.4", features = ["aio", "connection-manager", "tokio-comp"] }
thiserror = "2.0.12"
tokio = { version = "1.46.1", features = ["full"] }
