
services:

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "7005:6379"
    volumes:
      - redis-data:/data
    networks:
      - internal
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  redis-data:

networks:
  internal:
   name: aers_internal
